server:
  port: 8092
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.springframework.security: DEBUG
    com.thoughtmechanix: DEBUG
